# kindly generated by appropriated Rails generator
Mailjet.configure do |config|
  config.api_key = '2e527fec618b6ee2cade0254755e7ef9'
  config.secret_key = 'b3eecb3d257d9b61026b3f6a6319a3b5'
  config.default_from = 'gaspard.tertrais@gmail.com'
  # Mailjet API v3.1 is at the moment limited to Send API.
  # We’ve not set the version to it directly since there is no other endpoint in that version.
  # We recommend you create a dedicated instance of the wrapper set with it to send your emails.
  # If you're only using the gem to send emails, then you can safely set it to this version.
  # Otherwise, you can remove the dedicated line into config/initializers/mailjet.rb.
  config.api_version = 'v3.1'
end
